### PR TITLE
Working

### PR DESCRIPTION
**Pull request by pangos**
1. Worked on hot categories
2. COmpleted the home page

### CODE REVIEW

**Review by tsaffi — COMMENTED** [review]
Why did you removed the signup button

**Comment by tsaffi** [comment]
Because

**Comment by pangos** [comment]
Because ......

**Review by tsaffi — CHANGES_REQUESTED** [review]
The colors you used are not similar/identical to the ones in the design. Please check and fix it

**Review by tsaffi — APPROVED** [review]
Good job

**Pull request merged**
